apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: game-poller
  labels:
    workload.user.cattle.io/workloadselector: deployment-apps-game-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-apps-game-poller
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-apps-game-poller
    spec:
      containers:
      - name: game-poller
        image: thetablestop/game-poller
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: Production
        - name: NODE_PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: pod-env-vars
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        volumeMounts:
        - mountPath: /mnt/nodeshared
          name: nodeshared
      volumes:
      - hostPath:
          path: /mnt/host
          type: DirectoryOrCreate
        name: nodeshared
