stages:
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./.service.yml
  - applyYamlConfig:
      path: ./.ingress.yml
  - applyYamlConfig:
      path: ./.deployment.yml
      envFrom:
      - sourceName: connection-strings
        sourceKey: MONGODB_CONNECTION
        targetKey: MONGODB_CONNECTION
      - sourceName: connection-strings
        sourceKey: RABBITMQ_PUBSUB_CONNECTION
        targetKey: RABBITMQ_PUBSUB_CONNECTION
notification:
  recipients:
  - recipient: builds
    notifier: c-qgf2m:n-fldgj
  condition:
  - Success
  - Failed
